import { readdirSync, rmSync, statSync } from "node:fs";
import { join } from "node:path";
import { fileURLToPath } from "node:url";
import { NodeHost, compile, listServices } from "@typespec/compiler";
import { getVersions } from "@typespec/versioning";

/**
 * The independent conformance corpus: `@typespec/http-specs`.
 *
 * **Why a first-party corpus rather than more fixtures of our own.** A fixture we write tests what
 * we already thought of; `@typespec/http-specs` is Microsoft's own scenario set for validating
 * emitters, organised by the axes that actually break them - encoding, body-root and spread
 * parameters, multipart, content negotiation, encoded names, special words, streaming, versioning,
 * visibility, inheritance. It is the oracle precisely because we did not choose its contents.
 *
 * **Pinned exactly, and it must stay that way.** Every package here is `0.x` or `alpha`. A
 * floating range turns the committed baseline into a number that changes for reasons unrelated to
 * this emitter, which is the fastest way to make a gate meaningless.
 */

const here = fileURLToPath(new URL(".", import.meta.url));
export const packageRoot = join(here, "..", "..");
const specsRoot = join(packageRoot, "node_modules", "@typespec", "http-specs", "specs");

/**
 * The OpenAPI versions every document comparison is run against.
 *
 * **Stated once, because it was a literal in two repositories and neither knew about the other.**
 * `typespec-hono` runs the whole of this emitter and compares its own output against a document from
 * the same source; a version pinned here and a different one pinned there means the two halves are
 * graded against different contracts while both look green.
 *
 * **`3.2.0` is not decoration.** Measured over the whole corpus, exactly one scenario's documents
 * differ between 3.1.0 and 3.2.0 - `streaming/sse`, in three operations, where `schema` becomes
 * `itemSchema`. What that buys is not the diff itself: at 3.1 eight of nine SSE components are
 * unreachable from `paths` and the reachability walk excuses them, and at 3.2 five become reachable
 * through `itemSchema.oneOf[].properties.data.contentSchema`. Five component pairs this emitter
 * already declares go from excused to graded.
 *
 * **`3.0.0` is deliberately absent.** It is a different schema dialect - `nullable`, no `$ref`
 * siblings, `x-oai-` extensions - and grading against it would be a separate contract rather than a
 * second opinion on this one.
 */
export const GRADED_OPENAPI_VERSIONS = ["3.1.0", "3.2.0"] as const;

/**
 * Where `@typespec/openapi3` puts the documents for one spec version.
 *
 * **Measured, and it is the trap in this whole change.** Given ONE entry in `openapi-versions`,
 * openapi3 writes `<emitter-output-dir>/openapi.json`. Given MORE than one, it writes
 * `<emitter-output-dir>/<specVersion>/openapi.json`, and for a versioned service
 * `<specVersion>/openapi.<serviceVersion>.json`.
 *
 * A reader that assumes the flat layout finds **nothing** the moment a second version is added, and
 * nothing is not an error: in `typespec-hono` the equivalent code returns early and the scenario is
 * silently SKIPPED, so every arm passes having compared zero documents. `documentCount` in the
 * comparison is the floor that makes that impossible to miss here.
 */
export function openapiDirFor(openapiDir: string, specVersion: string): string {
	// Widened deliberately: the rule is openapi3's, about how many versions it was handed, and reading
	// it off the tuple's literal length would make the branch a constant the compiler folds away.
	const versions: readonly string[] = GRADED_OPENAPI_VERSIONS;
	return versions.length === 1 ? openapiDir : join(openapiDir, specVersion);
}

/** Where compiled scenario output lands. Gitignored; regenerated by the global setup. */
export const corpusOutDir = join(here, ".out");

export interface Scenario {
	/** `serialization/encoded-name/json` - stable, and what the baseline is keyed on. */
	readonly name: string;
	readonly mainFile: string;
}

/**
 * Every scenario in the corpus, in a stable order.
 *
 * Discovered rather than listed: a hand-maintained list silently stops covering what a corpus bump
 * adds, and the whole point of this harness is that its contents are not ours to choose. The count
 * is asserted by the suite so a discovery that finds nothing cannot pass as "all green".
 */
export function discoverScenarios(): readonly Scenario[] {
	const found: Scenario[] = [];
	const walk = (dir: string, segments: readonly string[]): void => {
		for (const entry of readdirSync(dir).toSorted()) {
			const full = join(dir, entry);
			if (entry === "main.tsp") {
				found.push({ name: segments.join("/"), mainFile: full });
				continue;
			}
			if (statSync(full).isDirectory()) walk(full, [...segments, entry]);
		}
	};
	walk(specsRoot, []);
	return found;
}

/**
 * The depth sources: fixtures compiled by BOTH emitters, alongside the corpus.
 *
 * **The corpus gives breadth and cannot give depth, and assuming otherwise made an arm vacuous.**
 * `@typespec/http-specs` tests protocol behaviour. Measured across every scenario it compiles, the
 * differential extracts **zero** constraints from either side - no `minLength`, no `pattern`, no
 * `minItems`. The constraint arm reported agreement while reading nothing at all.
 *
 * `test/reference/constraints.tsp` is written for exactly that gap: every constraint keyword the
 * emitter supports, once, on the type it is legal on. `service.tsp` joins it because the constructs
 * it carries - a discriminated base, a recursive model, an overlapping status set, content
 * negotiation - are ones this corpus does not reach either.
 *
 * `defaults.tsp` was added for the same reason and the gap it covers was the widest of the three:
 * measured across every compiled document in this repository, **zero** component schemas carried a
 * property-level `default`, so the keyword had never once been compared between the two artefacts.
 * That is how a default came to be implemented as an optionality - the one thing it is defined not
 * to be - without any arm noticing.
 *
 * These ARE ours, unlike the corpus, and that is a real weakness worth naming: a fixture we wrote
 * tests what we already thought of. They are depth on top of independent breadth, never a substitute
 * for it, which is why the corpus floors are asserted separately.
 */
export function depthSources(): readonly Scenario[] {
	const referenceDir = join(packageRoot, "test", "reference");
	return [
		{ name: "reference/constraints", mainFile: join(referenceDir, "constraints.tsp") },
		{ name: "reference/defaults", mainFile: join(referenceDir, "defaults.tsp") },
		{ name: "reference/service", mainFile: join(referenceDir, "service.tsp") },
	];
}

/**
 * Who failed, which is a different question from whether the scenario passed.
 *
 * **`oracle` is not our defect and must never be counted as one.** Measured on
 * `http-specs@0.1.0-alpha.40`: `routes` is refused by openapi3 itself
 * (`@typespec/openapi3/path-query` - OpenAPI cannot express a path containing a query string), and
 * `special-words` **crashes** openapi3 (`Cannot read properties of undefined (reading '0')`). For
 * those two there is no document to differentiate against, so the scenario is undifferentiable
 * rather than failing. Folding them into one number is how a corpus starts lying: the count would
 * move when Microsoft fix their emitter, and nobody would know whether we had regressed.
 */
export type FailureOwner = "ours" | "oracle";

export interface CompiledScenario {
	readonly scenario: Scenario;
	/** `undefined` when both emitters produced output. */
	readonly failure?: {
		readonly owner: FailureOwner;
		readonly code: string;
		readonly detail: string;
	};
	/** Directory holding this emitter's artefacts - `schemas.gen.ts` and its siblings. */
	readonly zodDir: string;
	/** Directory holding the OpenAPI document openapi3 produced from the same program. */
	readonly openapiDir: string;
	/** Warnings THIS emitter raised. Each one is a compromise it is shipping; there should be none. */
	readonly emitterWarnings?: readonly string[];
	/**
	 * The LAST version the service declares, when it is versioned.
	 *
	 * **Not the last document by filename, which is what this used to mean.** `versioning/removed`
	 * declares `v1, v2preview, v2`, so v2 is current - but the files sort as `openapi.v1.json`,
	 * `openapi.v2.json`, `openapi.v2preview.json`, and taking the last one compared us against a
	 * PREVIEW. The emitter had it right and the oracle was reading the wrong document, which is worth
	 * more than the one divergence it produced: seven sources are versioned, and any of them could as
	 * easily have been masked by an older version agreeing.
	 */
	readonly latestVersion?: string;
}

/** `@typespec/openapi3/path-query` -> `@typespec/openapi3`; our own codes have no prefix. */
function ownerOfCode(code: string): FailureOwner {
	return code.startsWith("@typespec/") ? "oracle" : "ours";
}

/**
 * An emitter that throws aborts the whole compile, so the thrown message is the only place the
 * culprit is named. Emitters run in declared order, which is why ours is declared first: if ours
 * throws, openapi3 never runs and the scenario is unambiguously ours.
 */
function ownerOfCrash(message: string): FailureOwner {
	return message.includes('"typespec-http-zod"') ? "ours" : "oracle";
}

/**
 * Compile one scenario with BOTH emitters, from one program.
 *
 * **One program, not two compiles.** The differential is only meaningful if both artefacts
 * describe the same types - recompiling would compare our output against a document built from a
 * separately-resolved program, and any disagreement would be ambiguous between "the emitter is
 * wrong" and "the two compiles differed".
 *
 * openapi3 is configured exactly as a consuming project's `tspconfig.yaml` configures it. An oracle
 * running with different options is not the oracle we ship against.
 */
export async function compileScenario(
	scenario: Scenario,
	/**
	 * Where this caller's corpus output lands.
	 *
	 * **A parameter, because a suite must never read output another suite wrote.** Vitest runs test
	 * files in parallel with nothing ordering them, so a sweep reading `corpusOutDir` would grade
	 * whichever build happened to be on disk - the defect that let a control pass green with the fix
	 * deleted from `src/`. Every caller owns a directory nobody else writes, and `isolation.test.ts`
	 * asserts it.
	 */
	outRoot: string = corpusOutDir,
): Promise<CompiledScenario> {
	const outputDir = join(outRoot, scenario.name.replaceAll("/", "__"));
	const dirs = { zodDir: join(outputDir, "zod"), openapiDir: join(outputDir, "openapi") };
	/**
	 * **Emptied first, so the comparison grades what THIS compile wrote.**
	 *
	 * `compileFixture` has done this since a control passed green against a previous run's output;
	 * the corpus harness, which is the larger oracle, did not - and it was measured doing exactly the
	 * same damage. Changing `openapi-versions` from one entry to two moves openapi3's output from
	 * `openapi/openapi.json` into `openapi/<version>/openapi.json`, and the superseded flat file
	 * stayed on disk looking current. A control that reinstated the flat-layout bug then **passed**,
	 * because `documentsIn` found the stale document from the run before it.
	 *
	 * A file the emitter has stopped producing is not evidence, and nothing about reading one looks
	 * wrong.
	 */
	rmSync(outputDir, { recursive: true, force: true });
	let program;
	try {
		program = await compile(NodeHost, scenario.mainFile, {
			outputDir,
			// Ours FIRST, deliberately - see `ownerOfCrash`.
			emit: ["typespec-http-zod", "@typespec/openapi3"],
			options: {
				"typespec-http-zod": {
					"emitter-output-dir": dirs.zodDir,
					/**
					 * **The emitted module must be self-contained, or the differential cannot load it.**
					 *
					 * A scenario declaring an enum emits `z.enum(SPEC_VOCABULARIES.Colors)`, which resolves
					 * only where the named contracts package exports `Colors`. Writing the vocabularies
					 * beside the schemas and importing them relatively is what makes the output stand alone
					 * - measured, 7 of 61 scenarios need it.
					 *
					 * **`contracts-package` has no default for exactly this reason.** It once defaulted to
					 * one repository's package name, so a consumer who configured nothing got validators
					 * importing from a package they had never heard of.
					 */
					"contracts-output-dir": dirs.zodDir,
					"contracts-package": "./vocabularies.gen.js",
					// Must match what openapi3 is given below. The two emitters answer the same question
					// about the same models and neither can read the other's options; setting one and not
					// the other is a contradiction, and this differential is precisely what reports it.
					"seal-object-schemas": true,
				},
				"@typespec/openapi3": {
					"emitter-output-dir": dirs.openapiDir,
					// One compile, every graded version - see `GRADED_OPENAPI_VERSIONS`. The TypeSpec compile
					// is the expensive half and happens once; only serialisation repeats, which is why
					// grading a second version costs 5% rather than doubling anything.
					"openapi-versions": [...GRADED_OPENAPI_VERSIONS],
					"seal-object-schemas": true,
					// JSON rather than the default YAML: the document is read back structurally, and a
					// YAML parser is a dependency this suite would otherwise take on purely to undo a
					// serialisation choice.
					"file-type": "json",
				},
			},
		});
	} catch (thrown) {
		const message = thrown instanceof Error ? thrown.message : String(thrown);
		// The useful line is the wrapped cause, not the "crashed! This is a bug." banner.
		const cause = /Error: (.*)/.exec(message)?.[1] ?? message.split("\n")[0] ?? message;
		return {
			scenario,
			...dirs,
			failure: {
				owner: ownerOfCrash(message),
				code: "emitter-crashed",
				detail: cause.slice(0, 200),
			},
		};
	}
	/**
	 * **Our own warnings are collected, not ignored, and there should be none.**
	 *
	 * The corpus raises warnings we neither own nor can fix - deprecations, and `metadata-ignored` on
	 * the very models that prove the metadata-position defect - so those are filtered out below. A
	 * warning THIS emitter raises is a different thing entirely: it means "the output is knowingly not
	 * what the document says, and we are shipping it anyway". There was one such warning for exactly
	 * one commit, marking an injected discriminator, and it was the wrong answer - a custom track with
	 * a label on it. Counting them keeps the next one from arriving quietly.
	 */
	/**
	 * Which version the emitter actually emitted, asked of the compiler rather than inferred.
	 *
	 * `getVersions` returns the versions in DECLARED order, which is the order that means anything -
	 * a version name sorts however its author spelled it.
	 */
	const latestVersion = ((): string | undefined => {
		for (const service of listServices(program)) {
			const [, versions] = getVersions(program, service.type);
			const declared = versions?.getVersions();
			const last = declared?.at(-1);
			if (last !== undefined) return last.value;
		}
		return undefined;
	})();

	const emitterWarnings = program.diagnostics
		.filter(
			(diagnostic) =>
				diagnostic.code.startsWith("typespec-http-zod/") && diagnostic.severity === "warning",
		)
		.map((diagnostic) => `${scenario.name} :: ${diagnostic.code}`);
	const error = program.diagnostics.find((diagnostic) => diagnostic.severity === "error");
	if (error === undefined) {
		return latestVersion === undefined
			? { scenario, ...dirs, emitterWarnings }
			: { scenario, ...dirs, emitterWarnings, latestVersion };
	}
	return {
		scenario,
		...dirs,
		failure: {
			owner: ownerOfCode(error.code),
			code: error.code,
			detail: String(error.message).split("\n")[0]?.slice(0, 200) ?? "",
		},
	};
}
